services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postales-db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=condorcoders'
      - 'TZ=UTC'
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.8
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=sa-east-1
    ports:
      - '4566:4566'
      - '4571:4571'
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d
    mem_limit: 512m
volumes:
  pgdata: {}
